### ISSUE TITLE
Some shapes can be simplified

### ISSUE THREAD

**Issue by iamvdo** [bennettfeely/Clippy#4]
For example, star can be written:

``` css
.star {
   clip-path: polygon(50% 0%, 82% 100%, 0 38%, 100% 38%, 18% 100%);
}
```

instead of:

``` css
.star {
   clip-path: polygon(50% 0%, 63% 38%, 100% 38%, 69% 59%, 82% 100%, 50% 75%, 18% 100%, 31% 59%, 0% 38%, 37% 38%);
}
```

Maybe you have a good reason to use more points?

Awesome tool btw. :)
